# Generated by Django 2.1.2 on 2018-11-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeblock',
            name='day',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
