# Generated by Django 2.1.2 on 2018-11-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20181106_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeblock',
            name='minutes',
        ),
        migrations.AddField(
            model_name='timeblock',
            name='duration',
            field=models.DurationField(default=None),
        ),
    ]
