# Generated by Django 2.1.2 on 2018-11-10 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20181106_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
